In [4]:
import pandas as pd
data = pd.read_csv("Solibility.csv")
data

,Unnamed: 0,MolLogP,MolWt,NumRotatableBonds,AromaticProportion,logS
0,0,2.59540,167.850,0.0,0.000000,-2.180
1,1,2.37650,133.405,0.0,0.000000,-2.000
2,2,2.59380,167.850,1.0,0.000000,-1.740
3,3,2.02890,133.405,1.0,0.000000,-1.480
4,4,2.91890,187.375,1.0,0.000000,-3.040
...,...,...,...,...,...,...
1139,1139,1.98820,287.343,8.0,0.000000,1.144
1140,1140,3.42130,286.114,2.0,0.333333,-4.925
1141,1141,3.60960,308.333,4.0,0.695652,-3.893
1142,1142,2.56214,354.815,3.0,0.521739,-3.790
1143,1143,2.02164,179.219,1.0,0.461538,-2.581

In [6]:
# Data Separation
X = data.drop("logS", axis=1)
Y = data["logS"]

0      -2.180
1      -2.000
2      -1.740
3      -1.480
4      -3.040
        ...
1139    1.144
1140   -4.925
1141   -3.893
1142   -3.790
1143   -2.581
Name: logS, Length: 1144, dtype: float64

In [8]:
# Data Splitting 
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(X, Y, test_size=0.2, random_state=10)
train_x

      Unnamed: 0  MolLogP    MolWt  NumRotatableBonds  AromaticProportion
41            41  3.45664  156.228                0.0            0.833333
668          668  1.44550  165.192                2.0            0.500000
1026        1026  1.83560  179.219                3.0            0.461538
892          892  3.36680  114.232                5.0            0.000000
326          326  1.10510  224.260                3.0            0.000000
...          ...      ...      ...                ...                 ...
256          256  1.05770  138.166                3.0            0.600000
1097        1097  1.34990  242.344                4.0            0.000000
1032        1032  2.87800  288.738                1.0            0.600000
733          733  3.99500  354.875                0.0            0.000000
527          527  3.51410  215.362                3.0            0.000000

[915 rows x 5 columns]

In [20]:
# Model Building 
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(train_x, train_y)
predict = model.predict(train_x)
predict
pre_test = model.predict(test_x)

In [27]:
# Model Performance
from sklearn.metrics import mean_squared_error, r2_score
train_mean = mean_squared_error(train_y, predict)
r2_train = r2_score(train_y, predict)
r2_test = r2_score(test_y, pre_test)
test_mean = mean_squared_error(test_y, pre_test)

In [35]:
# Printing Accuracy scores
# print(f"mean_squared_error (Train): {train_mean}")
# print(f"R2_Score (Train): {r2_train}")
# print(f"mean_squared_error (Test): {test_mean}")
# print(f"R2_Score (Test): {r2_test}")

# Making a Dataframe for these scores
Performance = pd.DataFrame(["Linear Regression", train_mean, r2_train, test_mean, r2_test]).transpose()
Performance.columns = ["Model", "MSB Train", "R2 Train", "MSB Test", "R2 Test"]
Performance

               Model MSB Train  R2 Train  MSB Test   R2 Test
0  Linear Regression  0.993173  0.775889  1.074731  0.745599

In [ ]:
# For Random Forest Model

# Evaluate the models