# Random State

In [35]:
from sklearn.model_selection import train_test_split
import pandas as pd

iris = pd.read_csv("E:\\iris.csv")
X = iris[['sepal.length', 'petal.length', 'sepal.width', 'petal.width']]
y = iris['variety']
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train

     sepal.length  petal.length  sepal.width  petal.width
91            6.1           4.6          3.0          1.4
135           7.7           6.1          3.0          2.3
69            5.6           3.9          2.5          1.1
128           6.4           5.6          2.8          2.1
114           5.8           5.1          2.8          2.4
..            ...           ...          ...          ...
133           6.3           5.1          2.8          1.5
137           6.4           5.5          3.1          1.8
72            6.3           4.9          2.5          1.5
140           6.7           5.6          3.1          2.4
37            4.9           1.4          3.6          0.1

[120 rows x 4 columns]